# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(570, 10, 171, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.configPanel = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.configPanel.setObjectName("configPanel")
        self.additionConfig = QtWidgets.QCheckBox(self.configPanel)
        self.additionConfig.setGeometry(QtCore.QRect(10, 20, 87, 20))
        self.additionConfig.setChecked(True)
        self.additionConfig.setObjectName("additionConfig")
        self.multiplicationConfig = QtWidgets.QCheckBox(self.configPanel)
        self.multiplicationConfig.setGeometry(QtCore.QRect(10, 90, 141, 20))
        self.multiplicationConfig.setChecked(True)
        self.multiplicationConfig.setObjectName("multiplicationConfig")
        self.timeTableConfig = QtWidgets.QRadioButton(self.configPanel)
        self.timeTableConfig.setEnabled(True)
        self.timeTableConfig.setGeometry(QtCore.QRect(30, 120, 100, 20))
        self.timeTableConfig.setChecked(False)
        self.timeTableConfig.setAutoExclusive(False)
        self.timeTableConfig.setObjectName("timeTableConfig")
        self.radioButton_2 = QtWidgets.QRadioButton(self.configPanel)
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 150, 100, 20))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.configPanel)
        self.radioButton_3.setEnabled(False)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 180, 100, 20))
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.configPanel)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 40, 100, 20))
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.substractionConfig = QtWidgets.QCheckBox(self.configPanel)
        self.substractionConfig.setGeometry(QtCore.QRect(10, 210, 141, 20))
        self.substractionConfig.setChecked(True)
        self.substractionConfig.setObjectName("substractionConfig")
        self.radioButton_5 = QtWidgets.QRadioButton(self.configPanel)
        self.radioButton_5.setGeometry(QtCore.QRect(30, 240, 100, 20))
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.checkBox = QtWidgets.QCheckBox(self.configPanel)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(10, 300, 87, 20))
        self.checkBox.setObjectName("checkBox")
        self.radioButton_6 = QtWidgets.QRadioButton(self.configPanel)
        self.radioButton_6.setEnabled(False)
        self.radioButton_6.setGeometry(QtCore.QRect(30, 270, 100, 20))
        self.radioButton_6.setChecked(False)
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.configPanel)
        self.radioButton_7.setEnabled(False)
        self.radioButton_7.setGeometry(QtCore.QRect(30, 60, 100, 20))
        self.radioButton_7.setChecked(False)
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName("radioButton_7")
        self.timeConfig = QtWidgets.QCheckBox(self.configPanel)
        self.timeConfig.setGeometry(QtCore.QRect(10, 330, 121, 20))
        self.timeConfig.setChecked(True)
        self.timeConfig.setObjectName("timeConfig")
        self.radioButton = QtWidgets.QRadioButton(self.configPanel)
        self.radioButton.setGeometry(QtCore.QRect(30, 360, 100, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_8 = QtWidgets.QRadioButton(self.configPanel)
        self.radioButton_8.setEnabled(False)
        self.radioButton_8.setGeometry(QtCore.QRect(30, 390, 100, 20))
        self.radioButton_8.setObjectName("radioButton_8")
        self.generateButton = QtWidgets.QPushButton(self.configPanel)
        self.generateButton.setGeometry(QtCore.QRect(0, 420, 171, 32))
        self.generateButton.setObjectName("generateButton")
        self.gridLayout.addWidget(self.configPanel, 2, 0, 1, 1)
        self.resultDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.resultDisplay.setGeometry(QtCore.QRect(0, 120, 541, 371))
        self.resultDisplay.setObjectName("resultDisplay")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(750, 10, 41, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.timetableGroup = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.timetableGroup.setContentsMargins(0, 0, 0, 0)
        self.timetableGroup.setObjectName("timetableGroup")
        self.timeTable1 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable1.setChecked(False)
        self.timeTable1.setObjectName("timeTable1")
        self.timetableGroup.addWidget(self.timeTable1)
        self.timeTable2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable2.setChecked(True)
        self.timeTable2.setObjectName("timeTable2")
        self.timetableGroup.addWidget(self.timeTable2)
        self.timeTable3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable3.setChecked(True)
        self.timeTable3.setObjectName("timeTable3")
        self.timetableGroup.addWidget(self.timeTable3)
        self.timeTable4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable4.setChecked(True)
        self.timeTable4.setObjectName("timeTable4")
        self.timetableGroup.addWidget(self.timeTable4)
        self.timeTable5 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable5.setChecked(True)
        self.timeTable5.setObjectName("timeTable5")
        self.timetableGroup.addWidget(self.timeTable5)
        self.timeTable6 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable6.setObjectName("timeTable6")
        self.timetableGroup.addWidget(self.timeTable6)
        self.timeTable7 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable7.setObjectName("timeTable7")
        self.timetableGroup.addWidget(self.timeTable7)
        self.timeTable8 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable8.setChecked(True)
        self.timeTable8.setObjectName("timeTable8")
        self.timetableGroup.addWidget(self.timeTable8)
        self.timeTable9 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable9.setObjectName("timeTable9")
        self.timetableGroup.addWidget(self.timeTable9)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 60, 16))
        self.label.setObjectName("label")
        self.operationAmountSlider = QtWidgets.QSlider(self.centralwidget)
        self.operationAmountSlider.setGeometry(QtCore.QRect(570, 520, 160, 22))
        self.operationAmountSlider.setMinimum(5)
        self.operationAmountSlider.setMaximum(35)
        self.operationAmountSlider.setPageStep(5)
        self.operationAmountSlider.setProperty("value", 20)
        self.operationAmountSlider.setSliderPosition(20)
        self.operationAmountSlider.setOrientation(QtCore.Qt.Horizontal)
        self.operationAmountSlider.setObjectName("operationAmountSlider")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 500, 141, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 895, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.configPanel.setTitle(_translate("MainWindow", "Configuration"))
        self.additionConfig.setText(_translate("MainWindow", "Addition"))
        self.multiplicationConfig.setText(_translate("MainWindow", "Multiplication"))
        self.timeTableConfig.setText(_translate("MainWindow", "Time Tables"))
        self.radioButton_2.setText(_translate("MainWindow", "Single Digit"))
        self.radioButton_3.setText(_translate("MainWindow", "Double Digit"))
        self.radioButton_4.setText(_translate("MainWindow", "Three Digits"))
        self.substractionConfig.setText(_translate("MainWindow", "Substraction"))
        self.radioButton_5.setText(_translate("MainWindow", "Three Digits"))
        self.checkBox.setText(_translate("MainWindow", "Division"))
        self.radioButton_6.setText(_translate("MainWindow", "Four Digits"))
        self.radioButton_7.setText(_translate("MainWindow", "Four Digits"))
        self.timeConfig.setText(_translate("MainWindow", "Time Telling"))
        self.radioButton.setText(_translate("MainWindow", "Analog"))
        self.radioButton_8.setText(_translate("MainWindow", "Digital"))
        self.generateButton.setText(_translate("MainWindow", "Generate"))
        self.timeTable1.setText(_translate("MainWindow", "1"))
        self.timeTable2.setText(_translate("MainWindow", "2"))
        self.timeTable3.setText(_translate("MainWindow", "3"))
        self.timeTable4.setText(_translate("MainWindow", "4"))
        self.timeTable5.setText(_translate("MainWindow", "5"))
        self.timeTable6.setText(_translate("MainWindow", "6"))
        self.timeTable7.setText(_translate("MainWindow", "7"))
        self.timeTable8.setText(_translate("MainWindow", "8"))
        self.timeTable9.setText(_translate("MainWindow", "9"))
        self.label.setText(_translate("MainWindow", "Preview"))
        self.label_2.setText(_translate("MainWindow", "Number of operations"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
