# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 50, 901, 471))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 10, 60, 16))
        self.label.setObjectName("label")
        self.resultDisplay = QtWidgets.QTextBrowser(self.tab)
        self.resultDisplay.setGeometry(QtCore.QRect(20, 30, 541, 371))
        self.resultDisplay.setObjectName("resultDisplay")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(810, 30, 41, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.timetableGroup = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.timetableGroup.setContentsMargins(0, 0, 0, 0)
        self.timetableGroup.setObjectName("timetableGroup")
        self.timeTable1 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable1.setChecked(False)
        self.timeTable1.setObjectName("timeTable1")
        self.timetableGroup.addWidget(self.timeTable1)
        self.timeTable2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable2.setChecked(True)
        self.timeTable2.setObjectName("timeTable2")
        self.timetableGroup.addWidget(self.timeTable2)
        self.timeTable3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable3.setChecked(True)
        self.timeTable3.setObjectName("timeTable3")
        self.timetableGroup.addWidget(self.timeTable3)
        self.timeTable4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable4.setChecked(True)
        self.timeTable4.setObjectName("timeTable4")
        self.timetableGroup.addWidget(self.timeTable4)
        self.timeTable5 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable5.setChecked(True)
        self.timeTable5.setObjectName("timeTable5")
        self.timetableGroup.addWidget(self.timeTable5)
        self.timeTable6 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable6.setObjectName("timeTable6")
        self.timetableGroup.addWidget(self.timeTable6)
        self.timeTable7 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable7.setObjectName("timeTable7")
        self.timetableGroup.addWidget(self.timeTable7)
        self.timeTable8 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable8.setChecked(True)
        self.timeTable8.setObjectName("timeTable8")
        self.timetableGroup.addWidget(self.timeTable8)
        self.timeTable9 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timeTable9.setObjectName("timeTable9")
        self.timetableGroup.addWidget(self.timeTable9)
        self.configPanel = QtWidgets.QGroupBox(self.tab)
        self.configPanel.setGeometry(QtCore.QRect(610, 0, 169, 441))
        self.configPanel.setObjectName("configPanel")
        self.addThreeDigits = QtWidgets.QRadioButton(self.configPanel)
        self.addThreeDigits.setGeometry(QtCore.QRect(30, 50, 100, 20))
        self.addThreeDigits.setChecked(True)
        self.addThreeDigits.setAutoExclusive(False)
        self.addThreeDigits.setObjectName("addThreeDigits")
        self.radioButton_5 = QtWidgets.QRadioButton(self.configPanel)
        self.radioButton_5.setGeometry(QtCore.QRect(30, 200, 100, 21))
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.configPanel)
        self.radioButton_6.setEnabled(False)
        self.radioButton_6.setGeometry(QtCore.QRect(30, 220, 100, 20))
        self.radioButton_6.setChecked(False)
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.addFourDigits = QtWidgets.QRadioButton(self.configPanel)
        self.addFourDigits.setEnabled(True)
        self.addFourDigits.setGeometry(QtCore.QRect(30, 70, 100, 20))
        self.addFourDigits.setChecked(False)
        self.addFourDigits.setAutoExclusive(True)
        self.addFourDigits.setObjectName("addFourDigits")
        self.additionAmountSlider = QtWidgets.QSlider(self.configPanel)
        self.additionAmountSlider.setGeometry(QtCore.QRect(20, 100, 141, 22))
        self.additionAmountSlider.setMinimum(0)
        self.additionAmountSlider.setMaximum(10)
        self.additionAmountSlider.setPageStep(5)
        self.additionAmountSlider.setProperty("value", 4)
        self.additionAmountSlider.setSliderPosition(4)
        self.additionAmountSlider.setOrientation(QtCore.Qt.Horizontal)
        self.additionAmountSlider.setObjectName("additionAmountSlider")
        self.label_6 = QtWidgets.QLabel(self.configPanel)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label_6.setObjectName("label_6")
        self.additionCount = QtWidgets.QLabel(self.configPanel)
        self.additionCount.setGeometry(QtCore.QRect(120, 30, 21, 16))
        self.additionCount.setObjectName("additionCount")
        self.multiplicationAmountSlider = QtWidgets.QSlider(self.configPanel)
        self.multiplicationAmountSlider.setGeometry(QtCore.QRect(20, 150, 141, 22))
        self.multiplicationAmountSlider.setMinimum(0)
        self.multiplicationAmountSlider.setMaximum(10)
        self.multiplicationAmountSlider.setPageStep(5)
        self.multiplicationAmountSlider.setProperty("value", 4)
        self.multiplicationAmountSlider.setSliderPosition(4)
        self.multiplicationAmountSlider.setOrientation(QtCore.Qt.Horizontal)
        self.multiplicationAmountSlider.setObjectName("multiplicationAmountSlider")
        self.multiplicationCount = QtWidgets.QLabel(self.configPanel)
        self.multiplicationCount.setGeometry(QtCore.QRect(120, 130, 21, 16))
        self.multiplicationCount.setObjectName("multiplicationCount")
        self.label_7 = QtWidgets.QLabel(self.configPanel)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.configPanel)
        self.label_8.setGeometry(QtCore.QRect(20, 180, 91, 16))
        self.label_8.setObjectName("label_8")
        self.substractionCount = QtWidgets.QLabel(self.configPanel)
        self.substractionCount.setGeometry(QtCore.QRect(120, 180, 21, 16))
        self.substractionCount.setObjectName("substractionCount")
        self.substractionAmountSlider = QtWidgets.QSlider(self.configPanel)
        self.substractionAmountSlider.setGeometry(QtCore.QRect(20, 240, 141, 22))
        self.substractionAmountSlider.setMinimum(0)
        self.substractionAmountSlider.setMaximum(10)
        self.substractionAmountSlider.setPageStep(5)
        self.substractionAmountSlider.setProperty("value", 4)
        self.substractionAmountSlider.setSliderPosition(4)
        self.substractionAmountSlider.setOrientation(QtCore.Qt.Horizontal)
        self.substractionAmountSlider.setObjectName("substractionAmountSlider")
        self.timeTellingAmountSlider = QtWidgets.QSlider(self.configPanel)
        self.timeTellingAmountSlider.setGeometry(QtCore.QRect(20, 390, 141, 22))
        self.timeTellingAmountSlider.setMinimum(0)
        self.timeTellingAmountSlider.setMaximum(10)
        self.timeTellingAmountSlider.setPageStep(5)
        self.timeTellingAmountSlider.setProperty("value", 3)
        self.timeTellingAmountSlider.setSliderPosition(3)
        self.timeTellingAmountSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeTellingAmountSlider.setObjectName("timeTellingAmountSlider")
        self.label_9 = QtWidgets.QLabel(self.configPanel)
        self.label_9.setGeometry(QtCore.QRect(20, 330, 81, 16))
        self.label_9.setObjectName("label_9")
        self.timeTellingCount = QtWidgets.QLabel(self.configPanel)
        self.timeTellingCount.setGeometry(QtCore.QRect(120, 330, 21, 16))
        self.timeTellingCount.setObjectName("timeTellingCount")
        self.timeDeltas = QtWidgets.QRadioButton(self.configPanel)
        self.timeDeltas.setGeometry(QtCore.QRect(40, 350, 100, 20))
        self.timeDeltas.setChecked(True)
        self.timeDeltas.setAutoExclusive(False)
        self.timeDeltas.setObjectName("timeDeltas")
        self.addDigital = QtWidgets.QRadioButton(self.configPanel)
        self.addDigital.setGeometry(QtCore.QRect(40, 370, 121, 20))
        self.addDigital.setChecked(True)
        self.addDigital.setAutoExclusive(False)
        self.addDigital.setObjectName("addDigital")
        self.label_10 = QtWidgets.QLabel(self.configPanel)
        self.label_10.setEnabled(True)
        self.label_10.setGeometry(QtCore.QRect(20, 270, 91, 16))
        self.label_10.setObjectName("label_10")
        self.divisionCount = QtWidgets.QLabel(self.configPanel)
        self.divisionCount.setEnabled(True)
        self.divisionCount.setGeometry(QtCore.QRect(120, 270, 21, 16))
        self.divisionCount.setObjectName("divisionCount")
        self.divisionAmountSlider = QtWidgets.QSlider(self.configPanel)
        self.divisionAmountSlider.setGeometry(QtCore.QRect(20, 290, 141, 22))
        self.divisionAmountSlider.setMinimum(0)
        self.divisionAmountSlider.setMaximum(10)
        self.divisionAmountSlider.setPageStep(5)
        self.divisionAmountSlider.setProperty("value", 3)
        self.divisionAmountSlider.setSliderPosition(3)
        self.divisionAmountSlider.setOrientation(QtCore.Qt.Horizontal)
        self.divisionAmountSlider.setObjectName("divisionAmountSlider")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(780, 10, 81, 16))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.resultDisplay_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.resultDisplay_2.setGeometry(QtCore.QRect(10, 30, 541, 371))
        self.resultDisplay_2.setObjectName("resultDisplay_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 60, 16))
        self.label_5.setObjectName("label_5")
        self.configPanel_2 = QtWidgets.QGroupBox(self.tab_2)
        self.configPanel_2.setGeometry(QtCore.QRect(600, 0, 169, 521))
        self.configPanel_2.setObjectName("configPanel_2")
        self.letterCheck = QtWidgets.QRadioButton(self.configPanel_2)
        self.letterCheck.setGeometry(QtCore.QRect(30, 40, 100, 20))
        self.letterCheck.setChecked(True)
        self.letterCheck.setAutoExclusive(False)
        self.letterCheck.setObjectName("letterCheck")
        self.numberCheck = QtWidgets.QRadioButton(self.configPanel_2)
        self.numberCheck.setEnabled(True)
        self.numberCheck.setGeometry(QtCore.QRect(30, 60, 100, 20))
        self.numberCheck.setChecked(True)
        self.numberCheck.setAutoExclusive(False)
        self.numberCheck.setObjectName("numberCheck")
        self.generateButton_2 = QtWidgets.QPushButton(self.configPanel_2)
        self.generateButton_2.setGeometry(QtCore.QRect(0, 490, 171, 32))
        self.generateButton_2.setObjectName("generateButton_2")
        self.label_11 = QtWidgets.QLabel(self.configPanel_2)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_11.setObjectName("label_11")
        self.spiralAmountSlider = QtWidgets.QSlider(self.configPanel_2)
        self.spiralAmountSlider.setGeometry(QtCore.QRect(10, 140, 141, 22))
        self.spiralAmountSlider.setMinimum(0)
        self.spiralAmountSlider.setMaximum(10)
        self.spiralAmountSlider.setPageStep(5)
        self.spiralAmountSlider.setProperty("value", 3)
        self.spiralAmountSlider.setSliderPosition(3)
        self.spiralAmountSlider.setOrientation(QtCore.Qt.Horizontal)
        self.spiralAmountSlider.setObjectName("spiralAmountSlider")
        self.emojiAmountSlider = QtWidgets.QSlider(self.configPanel_2)
        self.emojiAmountSlider.setGeometry(QtCore.QRect(10, 190, 141, 22))
        self.emojiAmountSlider.setMinimum(0)
        self.emojiAmountSlider.setMaximum(10)
        self.emojiAmountSlider.setPageStep(5)
        self.emojiAmountSlider.setProperty("value", 5)
        self.emojiAmountSlider.setSliderPosition(5)
        self.emojiAmountSlider.setOrientation(QtCore.Qt.Horizontal)
        self.emojiAmountSlider.setObjectName("emojiAmountSlider")
        self.label_12 = QtWidgets.QLabel(self.configPanel_2)
        self.label_12.setGeometry(QtCore.QRect(10, 170, 101, 16))
        self.label_12.setObjectName("label_12")
        self.spiralCount = QtWidgets.QLabel(self.configPanel_2)
        self.spiralCount.setGeometry(QtCore.QRect(110, 120, 21, 16))
        self.spiralCount.setObjectName("spiralCount")
        self.emojiCount = QtWidgets.QLabel(self.configPanel_2)
        self.emojiCount.setGeometry(QtCore.QRect(110, 170, 21, 16))
        self.emojiCount.setObjectName("emojiCount")
        self.gridAmountSlider = QtWidgets.QSlider(self.configPanel_2)
        self.gridAmountSlider.setGeometry(QtCore.QRect(10, 250, 141, 22))
        self.gridAmountSlider.setMinimum(0)
        self.gridAmountSlider.setMaximum(10)
        self.gridAmountSlider.setPageStep(5)
        self.gridAmountSlider.setProperty("value", 2)
        self.gridAmountSlider.setSliderPosition(2)
        self.gridAmountSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gridAmountSlider.setObjectName("gridAmountSlider")
        self.gridCount = QtWidgets.QLabel(self.configPanel_2)
        self.gridCount.setGeometry(QtCore.QRect(110, 230, 21, 16))
        self.gridCount.setObjectName("gridCount")
        self.label_13 = QtWidgets.QLabel(self.configPanel_2)
        self.label_13.setGeometry(QtCore.QRect(10, 230, 101, 16))
        self.label_13.setObjectName("label_13")
        self.letterAmountSlider = QtWidgets.QSlider(self.configPanel_2)
        self.letterAmountSlider.setGeometry(QtCore.QRect(10, 80, 141, 22))
        self.letterAmountSlider.setMinimum(0)
        self.letterAmountSlider.setMaximum(10)
        self.letterAmountSlider.setPageStep(5)
        self.letterAmountSlider.setProperty("value", 6)
        self.letterAmountSlider.setSliderPosition(6)
        self.letterAmountSlider.setOrientation(QtCore.Qt.Horizontal)
        self.letterAmountSlider.setObjectName("letterAmountSlider")
        self.label_14 = QtWidgets.QLabel(self.configPanel_2)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_14.setObjectName("label_14")
        self.letterCount = QtWidgets.QLabel(self.configPanel_2)
        self.letterCount.setGeometry(QtCore.QRect(110, 20, 21, 16))
        self.letterCount.setObjectName("letterCount")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_4.setObjectName("label_4")
        self.studentName = QtWidgets.QLineEdit(self.centralwidget)
        self.studentName.setGeometry(QtCore.QRect(20, 30, 101, 21))
        self.studentName.setObjectName("studentName")
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setGeometry(QtCore.QRect(620, 580, 171, 32))
        self.generateButton.setObjectName("generateButton")
        self.operationCount = QtWidgets.QLabel(self.centralwidget)
        self.operationCount.setGeometry(QtCore.QRect(760, 530, 21, 16))
        self.operationCount.setObjectName("operationCount")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 530, 141, 16))
        self.label_2.setObjectName("label_2")
        self.operationAmountSlider = QtWidgets.QSlider(self.centralwidget)
        self.operationAmountSlider.setEnabled(False)
        self.operationAmountSlider.setGeometry(QtCore.QRect(620, 550, 160, 22))
        self.operationAmountSlider.setMinimum(5)
        self.operationAmountSlider.setMaximum(35)
        self.operationAmountSlider.setPageStep(5)
        self.operationAmountSlider.setProperty("value", 20)
        self.operationAmountSlider.setSliderPosition(20)
        self.operationAmountSlider.setOrientation(QtCore.Qt.Horizontal)
        self.operationAmountSlider.setObjectName("operationAmountSlider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Preview"))
        self.timeTable1.setText(_translate("MainWindow", "1"))
        self.timeTable2.setText(_translate("MainWindow", "2"))
        self.timeTable3.setText(_translate("MainWindow", "3"))
        self.timeTable4.setText(_translate("MainWindow", "4"))
        self.timeTable5.setText(_translate("MainWindow", "5"))
        self.timeTable6.setText(_translate("MainWindow", "6"))
        self.timeTable7.setText(_translate("MainWindow", "7"))
        self.timeTable8.setText(_translate("MainWindow", "8"))
        self.timeTable9.setText(_translate("MainWindow", "9"))
        self.configPanel.setTitle(_translate("MainWindow", "Configuration"))
        self.addThreeDigits.setText(_translate("MainWindow", "Three Digits"))
        self.radioButton_5.setText(_translate("MainWindow", "Three Digits"))
        self.radioButton_6.setText(_translate("MainWindow", "Four Digits"))
        self.addFourDigits.setText(_translate("MainWindow", "Four Digits"))
        self.label_6.setText(_translate("MainWindow", "Additions:"))
        self.additionCount.setText(_translate("MainWindow", "0"))
        self.multiplicationCount.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Multiplications:"))
        self.label_8.setText(_translate("MainWindow", "Substractions:"))
        self.substractionCount.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Time Telling:"))
        self.timeTellingCount.setText(_translate("MainWindow", "0"))
        self.timeDeltas.setText(_translate("MainWindow", "Time Deltas"))
        self.addDigital.setText(_translate("MainWindow", "Digital && Analog"))
        self.label_10.setText(_translate("MainWindow", "Division:"))
        self.divisionCount.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Time Tables:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Primary"))
        self.label_5.setText(_translate("MainWindow", "Preview"))
        self.configPanel_2.setTitle(_translate("MainWindow", "Configuration"))
        self.letterCheck.setText(_translate("MainWindow", "Letters"))
        self.numberCheck.setText(_translate("MainWindow", "Numbers"))
        self.generateButton_2.setText(_translate("MainWindow", "Generate"))
        self.label_11.setText(_translate("MainWindow", "Spirals:"))
        self.label_12.setText(_translate("MainWindow", "Count Objects:"))
        self.spiralCount.setText(_translate("MainWindow", "0"))
        self.emojiCount.setText(_translate("MainWindow", "0"))
        self.gridCount.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "Grids:"))
        self.label_14.setText(_translate("MainWindow", "Letter Filling:"))
        self.letterCount.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Early Years"))
        self.label_4.setText(_translate("MainWindow", "Student Name:"))
        self.studentName.setText(_translate("MainWindow", " Bruno Garcia"))
        self.generateButton.setText(_translate("MainWindow", "Generate"))
        self.operationCount.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "Number of operations:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
